project_name: pgcenter
before:
  hooks:
  - go mod download
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: x86_64
    linux: Linux
  homepage: https://pgcenter.org
  maintainer: Alexey Lesovsky <lesovsky@gmail.com>
  description: Command-line admin tool for observing and troubleshooting Postgres.
  license: BSD-3
  formats:
    - deb
    - rpm
  bindir: /usr/bin
archive:
  replacements:
    amd64: x86_64
    linux: Linux
  files:
    - COPYRIGHT
    - README.md
    - doc/*
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - typo
