language: go
go:
  - "1.11.x"

dist: trusty
sudo: false

script:
  - env GO111MODULE=on make

before_deploy:
  - tar czf pgcenter.linux-amd64.tar.gz pgcenter
deploy:
  provider: releases
  api_key:
    secure: VWmFKklX8e8BxW+D8sINd9z7i4e9MLGQKXjELKzjr56KewM8tYdsXLzhhOuOV8dfod2Rm+V9HdtEuyzahowDCUHifoi6Dlt/bjdi7jerzDUvyg+RQZGapb4cdASi0G1RWwM2AHUBVhUoYMnWlA6tgkiPO6J9aoHtAgBqM9huCuZasUrmNupDOkE2Yi7qhVhFh1jx30m9YXz2WYhoqXL/vURY9UkHppzZva+909K48zIf1VLZmbXGkfJK4S5RkaCLQNAGOBLv2cwU3EFvH583T6oMtW7D4CDNVlUSt77b3tnOLULPlpzxdLAQq0HyVkwmlOzQ/tRbWYQSYcRFWPo6NfW8CQOXMYmGTUVaJc2I07vI6g2I+ol2E/4NR7+IqsYRIfI7gFYSGvfY17WpO5/pOhJXsa+1lwsPHxyQ4oK5LXd0TzcH7EIdC2uDHJ0u5o44D8s0zrKXtOfJBFggOiyOYtZ0O8/FJ9xTpstEdAm5k6BjafzUbkXfWbK1HK1vCewa+NENu3I19JVnBO2jVPVBxwhleYx+SxaHpz7poBkifed5M7lSmxlqK/jOtqXJerkvwMypVU4rse50knjGDBoi0tU71tccN9klA9rUJWJZK18G6Waozy+hdenPSUnWna5hTXRfGxd0uKXt59R0g7hpQUL9E1ZiwNVebDuXKMCscOw=
  skip_cleanup: true
  file: pgcenter.linux-amd64.tar.gz
  on:
    repo: lesovsky/pgcenter
    tags: true
